### ISSUE TITLE
Theme broken with thelounge v4

### ISSUE THREAD

**Issue by lowlevelm** [pattems/thelounge-theme-hexified#1]
The sidebar and popups seem to be working fine, but the main window is white. This applies to the pages: chat, add network, settings and help. See included screenshot.
<img width="1440" alt="Screen Shot 2020-01-13 at 1 39 27 AM" src="https://user-images.githubusercontent.com/26174395/72245528-a3128f80-35a5-11ea-991b-5a1bcd2e7715.png">

**Comment by pattems** [comment]
Hey there, thanks for your report! I haven't upgraded to v4 yet, so I wasn't aware of the issue. It looks like v4 made a lot of breaking changes to CSS, so I'm not sure yet how much work will be involved in fixing the theme, but hopefully I'll have everything sorted in the next couple days.

**Comment by pattems** [comment]
So having dived into it, enough's changed that to get the theme back _just so_, I'm going to have to spin up a v3 server and do a bunch of manual comparisons, but in the mean time, sticking this in the code block for the custom stylesheet will get you most of the look back:

```
:root {
	--window-bg-color: #25343a;
	--unread-marker-color: #2aa198;
	--date-marker-color: #2aa198;
	--body-color-muted: #839496;
}
.channel-list-item[data-type=lobby] { color: #268bd2; }
#footer button:hover, .channel-list-item:hover { background: #25343a; }
#chat .user-mode::before { display: none; }
#chat .user-mode { margin-bottom: 0; }
#form { background: var(--window-bg-color); }
#chat .userlist .count { background: unset; }
.channel-list-item.active { background-color: #25343a; }
#chat .msg[data-type=quit] .content { color: #6c71c4; }
#chat .msg[data-type=join] .content { color: #2aa198; }
#chat.colored-nicks .user.color-1, #chat.colored-nicks .user.color-18 { color: #2aa198; }
#chat.colored-nicks .user.color-2, #chat.colored-nicks .user.color-18 { color: #859900; }
#chat.colored-nicks .user.color-3, #chat.colored-nicks .user.color-19 { color: #dc322f; }
#chat.colored-nicks .user.color-4, #chat.colored-nicks .user.color-20 { color: #cb4b16; }
#chat.colored-nicks .user.color-5, #chat.colored-nicks .user.color-21 { color: #268bd2; }
#chat.colored-nicks .user.color-6, #chat.colored-nicks .user.color-22 { color: #2aa198; }
#chat.colored-nicks .user.color-7, #chat.colored-nicks .user.color-23 { color: #6c71c4; }
#chat.colored-nicks .user.color-8, #chat.colored-nicks .user.color-24 { color: #d33682; }
#chat.colored-nicks .user.color-9, #chat.colored-nicks .user.color-25 { color: #268bd2; }
#chat.colored-nicks .user.color-10, #chat.colored-nicks .user.color-26 { color: #6c71c4; }
#chat.colored-nicks .user.color-11, #chat.colored-nicks .user.color-27 { color: #dc322f; }
#chat.colored-nicks .user.color-12, #chat.colored-nicks .user.color-28 { color: #b58900; }
#chat.colored-nicks .user.color-13, #chat.colored-nicks .user.color-29 { color: #d33682; }
#chat.colored-nicks .user.color-14, #chat.colored-nicks .user.color-30 { color: #859900; }
#chat.colored-nicks .user.color-15, #chat.colored-nicks .user.color-31 { color: #b58900; }
#chat.colored-nicks .user.color-16, #chat.colored-nicks .user.color-32 { color: #cb4b16; }
#chat .count:before { color: unset; }
.channel-list-item.active .close { display: none; }
.channel-list-item.active[data-type=query] .close { display: unset; }
```

**Comment by pattems** [comment]
I believe that custom Stylesheet replicates all the theming done for hexified that's broken in v4, with the exception of the expanding topic on hover (or on tap, if on mobile). Once I've got that sorted, I'll push an update.

**Comment by lowlevelm** [comment]
This css code fixes the expanding topics, and links:
```css
.text, .toggle-content {
    background-color: #002b36 !important;
    color: #b7c5d1 !important;
}
```

**Comment by lowlevelm** [comment]
It has been some time since your last update. Do you know how long it will be before the update?

**Comment by pattems** [comment]
Hi there, sorry for the radio silence! I've been buried under work, but should have time to get the changes pushed tomorrow.

**Comment by pattems** [comment]
So tomorrow turned into a week, but I finally squeezed in the time to get it updated. It's pushed to NPM, and will be visible Soon™.
